basePath: /
definitions:
  github_com_oTeeLeko_product-service_internal_adapter_handler_dto.CreateProductRequest:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
      sale_price:
        type: number
    type: object
  github_com_oTeeLeko_product-service_internal_adapter_handler_dto.ProductResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      sale_price:
        type: number
    type: object
  github_com_oTeeLeko_product-service_internal_adapter_handler_dto.SimpleResponse:
    properties:
      error_code:
        type: string
      successful:
        type: boolean
    type: object
  github_com_oTeeLeko_product-service_internal_adapter_handler_dto.UpdateProductRequest:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
      sale_price:
        type: number
    type: object
  utils.APIResponse:
    properties:
      data: {}
      error_code:
        type: string
      successful:
        type: boolean
    type: object
info:
  contact: {}
  description: This is a sample product service API with Clean Architecture
  title: Product Service API
  version: "1.0"
paths:
  /product:
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Product data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_oTeeLeko_product-service_internal_adapter_handler_dto.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Product created successfully
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_oTeeLeko_product-service_internal_adapter_handler_dto.ProductResponse'
              type: object
      summary: Create Product
      tags:
      - Product
  /product/{id}:
    patch:
      consumes:
      - application/json
      description: Update an existing product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: Product data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_oTeeLeko_product-service_internal_adapter_handler_dto.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Product updated successfully
          schema:
            $ref: '#/definitions/github_com_oTeeLeko_product-service_internal_adapter_handler_dto.SimpleResponse'
      summary: Update Product
      tags:
      - Product
swagger: "2.0"
